### ISSUE TITLE
Stable yet?

### ISSUE THREAD

**Issue by geoffrowland** [dthies/tinymce4-mathslate#1]
Hi Daniel. Just wondering if you now consider tinymce4-mathslate to be a stable release version. E.g. any recent code 'tweaks' that need to be transferred from the Moodle version? The splash screen still has it as an RC. Thanks

**Comment by dthies** [comment]
Hi Geoff,
Thanks for the reminder. I had really changed anything, but the banner in the stable release, and forgot to update this version and the attached demo, but it should all be in sync now.
