### ISSUE TITLE
Using plugin on https app causes mixed content error when web page is served with https

### ISSUE THREAD

**Issue by mbucknell** [dthies/tinymce4-mathslate#5]

**Comment by mbucknell** [comment]
The yui content will need to be included in the repo since it is not available on https cdn. In addition, the mathjax library should be served via https and the styles.css can be served using relative paths.

**Comment by dthies** [comment]
I am not sure if bundling yui is the correct or to expect that the url should be configured on installation. I put this together as a prototype on the assumption that developers would modify would need to modify it for their applications. 
I have also done some work on an HTML5 version without YUI. It would make more sense for TinyMCE4 version to use jquery.

**Comment by mbucknell** [comment]
I started down that path, but quickly ran into the yui library trying to load further dependencies using http. A version that doesn't use YUI at all would be great.

**Comment by dthies** [comment]
I updated the files to load using relative references so http is not specified. The only exception is the reference in plugins/mathslate/mathslate.html to the YUI3 because Yahoo does not provide a https link. To use a local copy with https this should be changed to the appropriate value.
